from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from valideval.schemas import ConstructSpec, utc_now


def run_design_assistant(
    *,
    output_dir: str | Path,
    benchmark_id: str,
    construct: str,
    intended_decisions: str = "",
    item_format: str = "mcq",
    scoring_method: str = "exact_or_mcq",
    domain: str = "general",
    shortcuts: str = "",
    critical_fields: str = "",
    human_validation: str = "recommended",
    metrics: str = "",
    invalidating_conditions: str = "",
) -> dict[str, Any]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    threats = _threats_for(domain, shortcuts)
    critical = _split_csv(critical_fields) or _default_critical_fields(item_format)
    spec = ConstructSpec(
        claimed_construct=construct,
        construct_tags=[domain, item_format],
        construct_critical_fields=critical,
        expected_threats=threats,
        description=(
            "Construct scaffold generated by the design assistant. "
            "Benchmark authors should replace placeholders with protocol-specific details."
        ),
        limitations=[
            "Generated planning files are design scaffolds, not empirical validity evidence."
        ],
        metadata={
            "benchmark_id": benchmark_id,
            "intended_decisions": intended_decisions,
            "scoring_method": scoring_method,
            "human_validation": human_validation,
            "metrics": metrics,
            "invalidating_conditions": invalidating_conditions,
            "created_at": utc_now(),
        },
    )
    paths = {
        "construct_spec": output / "construct_spec.yaml",
        "audit_plan": output / "audit_plan.md",
        "benchmark_card_draft": output / "benchmark_card_draft.md",
        "human_validation_plan": output / "human_validation_plan.md",
        "threat_model": output / "threat_model.md",
    }
    paths["construct_spec"].write_text(
        yaml.safe_dump(spec.model_dump(mode="json"), sort_keys=False),
        encoding="utf-8",
    )
    paths["audit_plan"].write_text(
        _audit_plan(
            benchmark_id=benchmark_id,
            construct=construct,
            diagnostics=_diagnostics_for(domain),
            intended_decisions=intended_decisions,
            metrics=metrics,
        ),
        encoding="utf-8",
    )
    paths["benchmark_card_draft"].write_text(
        _card_draft(
            benchmark_id=benchmark_id,
            construct=construct,
            intended_decisions=intended_decisions,
            threats=threats,
            invalidating_conditions=invalidating_conditions,
        ),
        encoding="utf-8",
    )
    paths["human_validation_plan"].write_text(
        _human_plan(
            benchmark_id=benchmark_id,
            human_validation=human_validation,
            scoring_method=scoring_method,
        ),
        encoding="utf-8",
    )
    paths["threat_model"].write_text(
        _threat_model(
            benchmark_id=benchmark_id,
            domain=domain,
            threats=threats,
            shortcuts=shortcuts,
        ),
        encoding="utf-8",
    )
    return {
        "benchmark_id": benchmark_id,
        "output_dir": str(output),
        "files": {key: str(path) for key, path in paths.items()},
        "limitations": [
            "Assistant output is a benchmark-design scaffold and should be reviewed before preregistration."
        ],
    }


def _audit_plan(
    *,
    benchmark_id: str,
    construct: str,
    diagnostics: list[str],
    intended_decisions: str,
    metrics: str,
) -> str:
    return "\n".join(
        [
            f"# Audit Plan: {benchmark_id}",
            "",
            f"- Claimed construct: {construct}",
            f"- Intended decisions: {intended_decisions or 'TBD'}",
            f"- Primary metrics: {metrics or 'Report score distributions with uncertainty and diagnostics.'}",
            "",
            "## Minimum Diagnostics",
            "",
            *[f"- {diagnostic}" for diagnostic in diagnostics],
            "",
            "## Reporting Rule",
            "",
            "Report validity as a multidimensional evidence profile; do not collapse diagnostics into one scalar.",
            "",
        ]
    )


def _card_draft(
    *,
    benchmark_id: str,
    construct: str,
    intended_decisions: str,
    threats: list[str],
    invalidating_conditions: str,
) -> str:
    return "\n".join(
        [
            f"# Benchmark Card Draft: {benchmark_id}",
            "",
            "## Construct",
            "",
            construct,
            "",
            "## Intended Decisions",
            "",
            intended_decisions or "TBD",
            "",
            "## Possible Validity Threats",
            "",
            *[f"- {threat}" for threat in threats],
            "",
            "## Invalidating Conditions",
            "",
            invalidating_conditions or "Define conditions that would make claims unsupported.",
            "",
        ]
    )


def _human_plan(*, benchmark_id: str, human_validation: str, scoring_method: str) -> str:
    return "\n".join(
        [
            f"# Human Validation Plan: {benchmark_id}",
            "",
            f"- Coverage target: {human_validation}",
            f"- Scoring method to review: {scoring_method}",
            "- Include ambiguous, scorer-sensitive, and ranking-critical examples.",
            "- Report human agreement and judge-human agreement separately.",
            "- Human labels are evidence under a protocol, not perfect ground truth.",
            "",
        ]
    )


def _threat_model(
    *,
    benchmark_id: str,
    domain: str,
    threats: list[str],
    shortcuts: str,
) -> str:
    return "\n".join(
        [
            f"# Threat Model: {benchmark_id}",
            "",
            f"- Domain: {domain}",
            f"- Shortcut hypotheses: {shortcuts or 'TBD'}",
            "",
            "## Threats",
            "",
            *[f"- {threat}" for threat in threats],
            "",
            "## Limitations",
            "",
            "- Threats are hypotheses for diagnostics and repair review; they are not empirical findings.",
            "",
        ]
    )


def _threats_for(domain: str, shortcuts: str) -> list[str]:
    base = [
        "shortcut artifacts",
        "scoring ambiguity",
        "coverage gaps",
        "provenance gaps",
        "prompt or extraction sensitivity",
    ]
    domain_lower = domain.lower()
    if "rag" in domain_lower:
        base.extend(["retrieval leakage", "unsupported citations", "unanswerable imbalance"])
    elif "safety" in domain_lower:
        base.extend(["policy staleness", "judge bias", "refusal overgeneralization"])
    elif "code" in domain_lower:
        base.extend(["hidden-test weakness", "package/version sensitivity", "solution overlap"])
    elif "medical" in domain_lower:
        base.extend(["label ambiguity", "site shift", "clinically meaningless metric gains"])
    if shortcuts:
        base.append(f"author-specified shortcut hypothesis: {shortcuts}")
    return list(dict.fromkeys(base))


def _diagnostics_for(domain: str) -> list[str]:
    diagnostics = [
        "baselines",
        "answer_distribution",
        "shortcut",
        "reliability",
        "irt",
        "data_forensics",
        "human validation packet",
    ]
    domain_lower = domain.lower()
    if "rag" in domain_lower:
        diagnostics.extend(["rag_validity", "abstention_validity"])
    elif "safety" in domain_lower:
        diagnostics.extend(["paraphrase sensitivity", "rubric/judge sensitivity"])
    elif "code" in domain_lower:
        diagnostics.extend(["test strength report", "flaky reruns"])
    return diagnostics


def _default_critical_fields(item_format: str) -> list[str]:
    if item_format.lower() in {"mcq", "multiple_choice"}:
        return ["prompt", "choices", "answer"]
    if item_format.lower() in {"rag", "qa"}:
        return ["prompt", "context", "answer", "source_document"]
    return ["prompt", "answer"]


def _split_csv(value: str) -> list[str]:
    return [part.strip() for part in value.split(",") if part.strip()]
